name: CMake

on:
  push

env:
  BUILD_TYPE: Debug

jobs:
  windows:
    runs-on: windows-latest
    environment: env

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DAWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }} -DAWS_SECRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  macos:
    runs-on: macos-latest
    environment: env

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Xcode -DAWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }} -DAWS_SECRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
